version: '3'
services:
  web01:
    container_name: nginx01
    build: ./nginx01
    image: nginx01:1.0.0
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./nginx01/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../typescript/public/index.html:/usr/share/nginx/html/index.html
      - ../typescript/dist:/usr/share/nginx/html/dist
    extra_hosts:
      - "practice.local:127.0.0.1"